services:
  - type: web
    name: cadinfra-server
    env: python
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install -r server/requirements.txt

    startCommand: bash server/start.sh

    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: PYTHON_VERSION
        value: 3.13.5

    autoDeploy: true
    branch: main
    region: oregon
